name: Docker Image CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3

    - name: login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: xnsam/demo-llm:latest

    - name: log out from docker hub
      run: docker logout
